const vm=require('vm'),fs=require('fs'),path=require('path'),os=require('os'),assert=require('assert'),EventEmitter=require('events');
function node(tag='DIV'){return {tagName:tag,type:'',value:'',checked:true,hidden:false,disabled:false,children:[],options:[],listeners:{},attrs:{},setAttribute(k,v){this.attrs[k]=v},addEventListener(k,f){(this.listeners[k] ||= []).push(f)},appendChild(n){n.parentNode=this;this.children.push(n);if(n.tagName==='OPTION')this.options.push(n)},set textContent(v){this.text=String(v);this.children=[];this.options=[]},get textContent(){return this.text||''}};}
const ids=['model','reelAudio','reelRange','reelModel','reelStrength','reelKeep','reelSilence','reelPadding','reelGap','reelWindow','reelThreshold','reelRetakes','reelRemoveSilence','reelPreviewFirst','reelProfile','captionsTab','podcastTab','reelsTab','captionPage','podcastPage','reelsPage','reelRefresh','reelTimeline','reelStatus','reelReview','reelSummary','reelTakes','reelRun','reelCancel','reelImport','reelRebuild','reelFile'];
const els={};ids.forEach(id=>els[id]=node());els.model.options=[{value:'gigaam-uzbek',textContent:'UzScribe Uzbek'},{value:'large-v3',textContent:'UzScribe Global'}];els.model.value='gigaam-uzbek';
Object.entries({reelAudio:'0',reelRange:'auto',reelStrength:'safe',reelKeep:'complete',reelSilence:'.7',reelPadding:'.18',reelGap:'.65',reelWindow:'45',reelThreshold:'-42',reelProfile:'original'}).forEach(([k,v])=>els[k].value=v);
['reelRetakes','reelRemoveSilence','reelPreviewFirst'].forEach(id=>els[id].type='checkbox');els.reelPreviewFirst.checked=false;
const temp=fs.mkdtempSync(path.join(os.tmpdir(),'uzscribe-reels-panel-')),memory={};let autoClose=true,imports=0,importError=true,configs=[],info={host:'PPRO',name:'Original',identity:'1',trackCount:2,videoCount:1,start:0,duration:15};
const document={getElementById:id=>els[id],createElement:t=>node(t.toUpperCase()),uzscribe:{root:temp,mkdir:dir=>fs.mkdirSync(dir,{recursive:true}),python:{value:'python'},host(expression,cb){if(expression.startsWith('uzTimelineInfo'))cb(null,JSON.parse(JSON.stringify(info)));else if(expression.startsWith('uzPodcastExport'))cb(null,{success:true});else if(expression.startsWith('uzPodcastImport')){imports++;cb(importError?new Error('Import test error'):null,{success:!importError});}else throw Error(expression)}}};
function spawn(exe,args){assert.equal(exe,'python');const c=new EventEmitter();c.stdout=new EventEmitter();c.stderr=new EventEmitter();c.kill=()=>setImmediate(()=>c.emit('close',143));const output=args[args.indexOf('--output')+1];const settings=JSON.parse(fs.readFileSync(args[args.indexOf('--settings')+1],'utf8'));configs.push(settings);assert.equal(settings.model,'gigaam-uzbek');assert.equal(settings.strength,'safe');
if(autoClose)setImmediate(()=>{fs.writeFileSync(output,'<xmeml/>');fs.writeFileSync(output.replace(/\.xml$/,'.json'),JSON.stringify({output_seconds:6,removed_seconds:9,removed_retakes:1,retakes:[{id:0,start:1,end:4,text:'Takroriy gap.',kept_text:'Yaxshi gap.',remove:true}]}));c.emit('close',0)});return c;}
vm.runInNewContext(fs.readFileSync('adobe/UzbekSubtitles/reels-panel.js','utf8'),{document,require:n=>n==='child_process'?{spawn}:require(n),process,localStorage:{getItem:k=>memory[k],setItem:(k,v)=>memory[k]=v},JSON,Array,Object,Number,String,Date});
function click(id){if(!els[id].disabled)(els[id].listeners.click||[]).forEach(f=>f());}
(async()=>{document.uzscribeBusy=true;click('reelsTab');assert(!els.captionPage.hidden);document.uzscribeBusy=false;click('reelsTab');assert(els.captionPage.hidden && els.podcastPage.hidden && !els.reelsPage.hidden);
click('reelRun');assert(document.uzscribeBusy);click('podcastTab');assert(!els.reelsPage.hidden);await new Promise(setImmediate);assert.equal(imports,1);assert(!els.reelReview.hidden);assert(els.reelStatus.textContent.includes('Import test error'));assert(!els.reelImport.hidden);
importError=false;click('reelImport');assert.equal(imports,2);assert(els.reelImport.hidden);
// Restore a selected take, preview without automatically importing another sequence.
els.reelTakes.children[0].children[0].children[0].checked=true;els.reelPreviewFirst.checked=true;click('reelRebuild');await new Promise(setImmediate);assert.deepEqual(configs[1].keep_retake_ids,[0]);assert.equal(imports,2);assert(!els.reelImport.hidden);
// A different active sequence cannot reuse the old snapshot.
info.identity='2';click('reelRebuild');assert(els.reelStatus.textContent.includes('Avvalgi sequence'));assert.equal(configs.length,2);info.identity='1';
autoClose=false;click('reelRun');click('reelCancel');await new Promise(setImmediate);assert(!document.uzscribeBusy);assert.equal(imports,2);assert(els.reelStatus.textContent.includes('Bekor'));
info.host='AEFT';click('reelRun');assert(!document.uzscribeBusy);assert(els.reelStatus.textContent.includes('Premiere'));
fs.rmSync(temp,{recursive:true,force:true});console.log('Reels one-click import, retry, take restore, preview, cancel and sequence guards OK');})().catch(e=>{console.error(e);fs.rmSync(temp,{recursive:true,force:true});process.exitCode=1});
