const vm=require('vm'),fs=require('fs'),path=require('path'),os=require('os'),assert=require('assert'),EventEmitter=require('events');
function node(tag='DIV'){return {tagName:tag,type:'',value:'',checked:true,hidden:false,disabled:false,children:[],options:[],listeners:{},attrs:{},setAttribute(k,v){this.attrs[k]=v},addEventListener(k,f){(this.listeners[k] ||= []).push(f)},appendChild(n){n.parentNode=this;this.children.push(n);if(n.tagName==='OPTION')this.options.push(n)},removeChild(n){this.children.splice(this.children.indexOf(n),1)},set textContent(v){this.text=String(v);this.children=[];this.options=[]},get textContent(){return this.text||''}};}
const ids=['podcastPage','captionPage','podcastTab','captionsTab','podRange','podMode','podShot','podReaction','podSilence','podPadding','podThreshold','podMargin','podWideEvery','podRemove','podProfile','podStatus','podMappings','podWide','podTimeline','podAdd','podRefresh','podRun','podCancel','podImport','podReset','podReview','podSummary','podCuts','podFile'];
const els={};ids.forEach(id=>els[id]=node());
Object.entries({podRange:'auto',podMode:'cameras',podShot:'2.5',podReaction:'.35',podSilence:'1',podPadding:'.2',podThreshold:'-42',podMargin:'3',podWideEvery:'30',podProfile:'original'}).forEach(([k,v])=>els[k].value=v);els.podRemove.type='checkbox';
const temp=fs.mkdtempSync(path.join(os.tmpdir(),'uzscribe-panel-')), memory={};
let autoClose=true,imports=0,importError=false,info={host:'PPRO',name:'Test',identity:'1',trackCount:4,videoCount:5,start:0,duration:12,fps:25};
const document={getElementById:id=>els[id],createElement:t=>node(t.toUpperCase()),uzscribe:{root:temp,mkdir:dir=>fs.mkdirSync(dir,{recursive:true}),python:{value:'python'},host(expression,cb){if(expression.startsWith('uzTimelineInfo'))cb(null,info);else if(expression.startsWith('uzPodcastExport'))cb(null,{success:true});else if(expression.startsWith('uzPodcastImport')){imports++;cb(importError?new Error('Test import failure'):null,{success:!importError});}else throw Error(expression)}}};
function spawn(exe,args){assert.equal(exe,'python');const c=new EventEmitter();c.stdout=new EventEmitter();c.stderr=new EventEmitter();c.kill=()=>setImmediate(()=>c.emit('close',143));const output=args[args.indexOf('--output')+1];const settings=JSON.parse(fs.readFileSync(args[args.indexOf('--settings')+1],'utf8'));assert.equal(settings.speakers.length,4);assert.equal(settings.minimum_shot,2.5);
if(autoClose)setImmediate(()=>{fs.writeFileSync(output,'<xmeml/>');fs.writeFileSync(output.replace(/\.xml$/,'.json'),JSON.stringify({output_seconds:10,removed_seconds:2,fps:25,cuts:[{start:0,end:100,camera:0}],output_frames:250}));c.emit('close',0)});return c;}
vm.runInNewContext(fs.readFileSync('adobe/UzbekSubtitles/podcast-panel.js','utf8'),{document,require:n=>n==='child_process'?{spawn}:require(n),process,localStorage:{getItem:k=>memory[k],setItem:(k,v)=>memory[k]=v},JSON,Array,Object,Number,String,Date});
function click(id){if(!els[id].disabled)(els[id].listeners.click||[]).forEach(f=>f());}
(async()=>{document.uzscribeBusy=true;click('podcastTab');assert(!els.captionPage.hidden);document.uzscribeBusy=false;click('podcastTab');assert(els.captionPage.hidden);assert.equal(els.podMappings.children.length,1);for(let i=0;i<3;i++)click('podAdd');assert.equal(els.podMappings.children.length,4);assert.equal(JSON.parse(memory['uzscribe.podcast.v1']).rows.length,4);
click('podRun');assert(document.uzscribeBusy);click('captionsTab');assert(els.captionPage.hidden);await new Promise(setImmediate);assert(!els.podReview.hidden);assert(!els.podImport.hidden);assert(!document.uzscribeBusy);
importError=true;click('podImport');assert.equal(imports,1);assert(!els.podReview.hidden);assert(els.podStatus.textContent.includes('failure'));importError=false;click('podImport');assert.equal(imports,2);assert(els.podImport.hidden);
click('podReset');autoClose=false;click('podRun');click('podCancel');await new Promise(setImmediate);assert(!document.uzscribeBusy);assert.equal(imports,2);assert(els.podStatus.textContent.includes('Bekor'));
info.host='AEFT';click('podRefresh');assert(els.podTimeline.textContent.includes('Premiere'));click('podRun');assert(!document.uzscribeBusy);assert.equal(imports,2);
fs.rmSync(temp,{recursive:true,force:true});console.log('Podcast configurable mappings, review/import retry, cancel and shared busy guard OK');})().catch(e=>{console.error(e);fs.rmSync(temp,{recursive:true,force:true});process.exitCode=1});
