const vm=require('vm'),fs=require('fs'),path=require('path'),os=require('os'),EventEmitter=require('events');
const ids=['python','premierePreset','batchDir','batchRun','model','compareModel','retryModel','script','captionMode','animation','animationField','animationHint','exportVtt','exportAss','detectSpeakers','speakerCount','speakerChoice','assignSpeaker','modelHint','fps','range','audioTrack','style','lines','words','chars','duration','pause','restoreSentences','splitSentences','splitCommas','splitPauses','startPad','endPad','minCue','glossary','preview','boundaryPreview','run','cancel','reviewSection','reviewInfo','srtEditor','cueText','cueList','waveform','retryCue','compareText','applyReview','discardReview','mainActions','workActions','reviewActions','refresh','timeline','status','advanced'];
const els={};for(const id of ids)els[id]={id,value:'',checked:true,open:false,hidden:false,disabled:false,textContent:'',type:id.startsWith('split')||id==='restoreSentences'?'checkbox':'text',tagName:['model','range','style'].includes(id)?'SELECT':'INPUT',options:[],listeners:{},addEventListener(k,f){(this.listeners[k]??=[]).push(f)},insertBefore(o){this.options.unshift(o)},appendChild(o){this.options.push(o)}};
els.cueList.appendChild=()=>{};
for(const [id,value] of Object.entries({model:'large-v3',compareModel:'',script:'latin',captionMode:'normal',animation:'none',speakerCount:'auto',range:'auto',audioTrack:'all',style:'medium',fps:'25',lines:'2',words:'3',chars:'42',duration:'5',pause:'0.65',startPad:'0',endPad:'0',minCue:'0.8'}))els[id].value=value;
els.detectSpeakers.checked=false;
for(const [id,values] of Object.entries({model:['large-v3','medium','small'],range:['auto','inout','full'],audioTrack:['all'],style:['short','medium','long','custom']}))els[id].options=values.map(value=>({value}));
let autoClose=true,imports=0,importError=false,generated='';
function mockRequire(name){if(name==='fs')return Object.assign({},fs,{existsSync:p=>String(p).endsWith('.epr')||fs.existsSync(p)});if(name!=='child_process')return require(name);return {spawn:(_exe,args)=>{const retry=args.includes('--start-seconds');if(!retry&&args[args.indexOf('--replace')+1]!=='salom=assalom')throw Error('glossary not passed to CLI');const c=new EventEmitter();c.stderr=new EventEmitter();c.kill=()=>setImmediate(()=>c.emit('close',143));const output=args[args.indexOf('--output')+1];if(!retry)generated=output;if(autoClose||retry)setImmediate(()=>{fs.writeFileSync(output,retry?'\uFEFF1\n00:00:00,000 --> 00:00:01,000\nYangi.\n':'\uFEFF1\n00:00:00,000 --> 00:00:01,000\nSalom.\n');if(retry)fs.writeFileSync(output.replace(/\.srt$/,'.json'),JSON.stringify({words:[{start:0,end:1,text:'Yangi.',confidence:.8}]}));c.emit('close',0)});return c}}}
const info={name:'Test',identity:'test-sequence-id',duration:8,start:0,marked:false,fps:25,host:'PPRO'};
let composerOpened=0,composerExpression='';
const cep={evalScript:(script,cb)=>{if(script.includes('uzTimelineInfo('))cb(JSON.stringify(info));else if(script.includes('uzExportAudio('))cb(JSON.stringify({path:path.join(os.tmpdir(),'fake-uzbek.wav'),name:'Test',identity:info.identity}));else if(script.includes('uzImportCaptions(')){imports++;cb(importError?'{"error":"Sinov xatosi"}':'{"success":true}')}else if(script.includes('importUzbekSrt(')){composerExpression=script;cb('1 ta vaqtli matn qatlami yaratildi.')}else throw Error(script)},requestOpenExtension:(id)=>{if(id!=='com.misterhorse.animationcomposer.browser')throw Error('wrong extension');composerOpened++}};
const memory={};const fakeProcess=Object.assign({},process,{platform:process.argv.includes('--windows')?'win32':process.platform,env:Object.assign({},process.env,{ProgramFiles:'/fake/Program Files',LOCALAPPDATA:'/fake/Local'})});const context={require:mockRequire,document:{getElementById:id=>els[id],createElement:()=>({appendChild(){}})},process:fakeProcess,__dirname:path.resolve('adobe/UzbekSubtitles'),__adobe_cep__:cep,localStorage:{getItem:k=>memory[k]||null,setItem:(k,v)=>memory[k]=v},JSON,Math,Date,Number,isFinite,String,Array,Object};
vm.runInNewContext(fs.readFileSync('adobe/UzbekSubtitles/panel.js','utf8'),context);
(async()=>{els.glossary.value='ikki so‘z = bitta';els.run.onclick();if(!els.status.textContent.includes('Lug‘atning 1-qatorini'))throw Error('invalid glossary accepted');els.glossary.value='salom = assalom';els.run.onclick();await new Promise(setImmediate);if(els.reviewSection.hidden||!els.srtEditor.value.includes('Salom'))throw Error('review did not open');
els.cueText.value='Oson tahrir.';els.cueText.oninput();if(!els.srtEditor.value.includes('Oson tahrir.'))throw Error('simple cue editor did not update SRT');
els.retryCue.onclick();await new Promise(setImmediate);if(!els.srtEditor.value.includes('Yangi.'))throw Error('selected cue retry failed');
els.speakerChoice.value='SPEAKER_01';els.assignSpeaker.onclick();if(!els.status.textContent.includes('So‘zlovchi'))throw Error('speaker label not assigned');
els.srtEditor.value='1\n00:00:01,000 --> 00:00:00,000\nXato\n';els.applyReview.onclick();if(els.reviewSection.hidden||!els.status.textContent.includes('tekshiring'))throw Error('bad SRT accepted');
els.srtEditor.value='1\n00:00:00,000 --> 00:00:01,000\nTo‘g‘ri.\n';importError=true;els.applyReview.onclick();if(imports!==1||els.reviewSection.hidden||!els.status.textContent.includes('Sinov xatosi'))throw Error('failed import did not preserve review');
importError=false;els.applyReview.onclick();if(imports!==2||els.mainActions.hidden||!fs.readFileSync(generated,'utf8').includes('To‘g‘ri'))throw Error('review import failed');if(!fs.readFileSync(generated.replace(/\.srt$/,'.json'),'utf8').includes('SPEAKER_01'))throw Error('speaker label not saved');for(const ext of ['.srt','.json','.vtt','.ass'])try{fs.unlinkSync(generated.replace(/\.srt$/,ext))}catch(e){}
autoClose=false;els.run.onclick();els.cancel.onclick();await new Promise(setImmediate);if(imports!==2||els.mainActions.hidden||!els.status.textContent.includes('Bekor'))throw Error('cancel failed');
autoClose=true;info.host='AEFT';els.animation.value='composer';els.run.onclick();await new Promise(setImmediate);if(els.reviewSection.hidden)throw Error('AE review did not open');els.applyReview.onclick();if(composerOpened!==1||!composerExpression.includes(',true)'))throw Error('Animation Composer handoff failed');
console.log('Simple review, validation, cancellation and Composer handoff OK')})().catch(e=>{console.error(e);process.exitCode=1});
