const vm=require('vm'),fs=require('fs'),path=require('path'),os=require('os'),EventEmitter=require('events');
const ids=['python','model','modelHint','fps','range','style','lines','words','chars','duration','pause','splitSentences','splitCommas','splitPauses','startPad','endPad','minCue','glossary','preview','boundaryPreview','run','reviewRun','cancel','reviewSection','reviewInfo','srtEditor','applyReview','discardReview','mainActions','workActions','reviewActions','refresh','timeline','status','advanced'];
const els={};for(const id of ids)els[id]={id,value:'',checked:true,open:false,hidden:false,disabled:false,textContent:'',type:id.startsWith('split')?'checkbox':'text',tagName:['model','range','style'].includes(id)?'SELECT':'INPUT',options:[],listeners:{},addEventListener(k,f){(this.listeners[k]??=[]).push(f)},insertBefore(o){this.options.unshift(o)}};
for(const [id,value] of Object.entries({model:'large-v3',range:'auto',style:'medium',fps:'25',lines:'2',words:'3',chars:'42',duration:'5',pause:'0.65',startPad:'0',endPad:'0',minCue:'0.8'}))els[id].value=value;
for(const [id,values] of Object.entries({model:['large-v3','medium','small'],range:['auto','inout','full'],style:['short','medium','long','custom']}))els[id].options=values.map(value=>({value}));
let autoClose=true,imports=0,importError=false,generated='';
function mockRequire(name){if(name==='fs')return Object.assign({},fs,{existsSync:p=>String(p).endsWith('.epr')||fs.existsSync(p)});if(name!=='child_process')return require(name);return {spawn:(_exe,args)=>{if(args[args.indexOf('--replace')+1]!=='salom=assalom')throw Error('glossary not passed to CLI');const c=new EventEmitter();c.stderr=new EventEmitter();c.kill=()=>setImmediate(()=>c.emit('close',143));generated=args[args.indexOf('--output')+1];if(autoClose)setImmediate(()=>{fs.writeFileSync(generated,'\uFEFF1\n00:00:00,000 --> 00:00:01,000\nSalom.\n');c.emit('close',0)});return c}}}
const info={name:'Test',identity:'test-sequence-id',duration:8,start:0,marked:false,fps:25,host:'PPRO'};
const cep={evalScript:(script,cb)=>{if(script.includes('uzTimelineInfo('))cb(JSON.stringify(info));else if(script.includes('uzExportAudio('))cb(JSON.stringify({path:path.join(os.tmpdir(),'fake-uzbek.wav'),name:'Test',identity:info.identity}));else if(script.includes('uzImportCaptions(')){imports++;cb(importError?'{"error":"Sinov xatosi"}':'{"success":true}')}else throw Error(script)}};
const memory={};const context={require:mockRequire,document:{getElementById:id=>els[id],createElement:()=>({})},process,__dirname:path.resolve('adobe/UzbekSubtitles'),__adobe_cep__:cep,localStorage:{getItem:k=>memory[k]||null,setItem:(k,v)=>memory[k]=v},JSON,Math,Date,Number,isFinite,String,Array,Object};
vm.runInNewContext(fs.readFileSync('adobe/UzbekSubtitles/panel.js','utf8'),context);
(async()=>{els.glossary.value='ikki so‘z = bitta';els.reviewRun.onclick();if(!els.status.textContent.includes('Lug‘atning 1-qatorini'))throw Error('invalid glossary accepted');els.glossary.value='salom = assalom';els.reviewRun.onclick();await new Promise(setImmediate);if(els.reviewSection.hidden||!els.srtEditor.value.includes('Salom'))throw Error('review did not open');
els.srtEditor.value='1\n00:00:01,000 --> 00:00:00,000\nXato\n';els.applyReview.onclick();if(els.reviewSection.hidden||!els.status.textContent.includes('tekshiring'))throw Error('bad SRT accepted');
els.srtEditor.value='1\n00:00:00,000 --> 00:00:01,000\nTo‘g‘ri.\n';importError=true;els.applyReview.onclick();if(imports!==1||els.reviewSection.hidden||!els.status.textContent.includes('Sinov xatosi'))throw Error('failed import did not preserve review');
importError=false;els.applyReview.onclick();if(imports!==2||els.mainActions.hidden||!fs.readFileSync(generated,'utf8').includes('To‘g‘ri'))throw Error('review import failed');fs.unlinkSync(generated);
autoClose=false;els.run.onclick();els.cancel.onclick();await new Promise(setImmediate);if(imports!==2||els.mainActions.hidden||!els.status.textContent.includes('Bekor'))throw Error('cancel failed');console.log('Review, validation, retry and cancellation OK')})().catch(e=>{console.error(e);process.exitCode=1});
