(function(){'use strict';var fs=require('fs'),path=require('path'),crypto=require('crypto'),https=require('https'),core=require(path.join(__dirname,'license-core.js'));
var el=function(id){return document.getElementById(id)},devRoot=path.resolve(fs.realpathSync(__dirname),'..','..'),os=require('os'),userData=process.platform==='win32'?path.join(process.env.LOCALAPPDATA||path.join(os.homedir(),'AppData','Local'),'UzbekSubtitles'):path.join(os.homedir(),'Library','Application Support','UzbekSubtitles'),root=fs.existsSync(path.join(userData,'subtitles','cli.py'))?userData:devRoot,folder=path.join(root,'license'),statePath=path.join(folder,'state.json'),config={},state={},device='';
function mkdir(p){if(fs.existsSync(p))return;var parent=path.dirname(p);if(parent!==p)mkdir(parent);try{fs.mkdirSync(p,448)}catch(e){if(!fs.existsSync(p))throw e;}}
function save(){mkdir(folder);var temp=statePath+'.tmp-'+crypto.randomBytes(6).toString('hex');try{fs.writeFileSync(temp,JSON.stringify(state),{mode:384,flag:'wx'});fs.renameSync(temp,statePath);}finally{if(fs.existsSync(temp))fs.unlinkSync(temp);}}
function message(text){el('licenseStatus').textContent=text;}
try{config=JSON.parse(fs.readFileSync(path.join(__dirname,'license-config.json'),'utf8'));if(fs.existsSync(statePath))state=JSON.parse(fs.readFileSync(statePath,'utf8'));mkdir(folder);var identity=path.join(folder,'installation-id');if(!fs.existsSync(identity)){try{fs.writeFileSync(identity,crypto.randomBytes(32).toString('hex'),{mode:384,flag:'wx'});}catch(createError){if(createError.code!=='EEXIST')throw createError;}}device=crypto.createHash('sha256').update(fs.readFileSync(identity,'utf8')).digest('hex');}catch(e){message('Obuna sozlamasi o‘qilmadi: '+e.message);}
function valid(feature){if(config.mode==='community')return true;if(config.mode!=='subscription')throw Error('Obuna sozlamasi noto‘g‘ri.');return core.validate(state.token,config.public_key,device,Date.now()/1000,state.last_seen,feature);}
function showState(){if(config.mode==='community'){message('Beta rejimi · obuna serveri hali ulanmagan.');return;}try{var c=valid();message('Pro faol · '+new Date(c.subscription_expires_at*1000).toLocaleDateString()+' gacha.');}catch(e){message(e.message);}}
function request(route,body,callback){
  if(!/^https:\/\/[^\s]+$/.test(config.api_url||'')){callback(Error('Obuna serveri hali ulanmagan.'));return;}
  var data=body?JSON.stringify(body):'',url=config.api_url.replace(/\/$/,'')+route,done=false;
  function finish(e,j){if(done)return;done=true;callback(e,j);}
  var target=new (require('url').URL)(url);var options={protocol:target.protocol,hostname:target.hostname,port:target.port,path:target.pathname+target.search,method:body?'POST':'GET'};options.headers={'Content-Type':'application/json',Authorization:state.key?'Bearer '+state.key:'','Content-Length':Buffer.byteLength(data)};
  var req=https.request(options,function(res){var raw='';res.on('data',function(chunk){raw+=chunk;if(raw.length>65536){req.destroy();finish(Error('Server javobi katta.'));}});res.on('end',function(){try{var j=JSON.parse(raw);var problem=res.statusCode>=400?Error(j.error||'Server xatosi'):null;if(problem)problem.status=res.statusCode;finish(problem,j);}catch(e){finish(Error('Server javobi o‘qilmadi.'));}});});
  req.setTimeout(12000,function(){req.destroy();finish(Error('Server javob bermadi.'));});req.on('error',function(e){finish(e);});if(data)req.write(data);req.end();
}
function refresh(){if(config.mode!=='subscription' || !state.key){showState();return;}request('/api/activate',{device_id:device,label:process.platform==='win32'?'Windows':'macOS'},function(e,j){if(e){if(e.status===401||e.status===403){state.token='';try{save();}catch(writeError){}message(e.message);return;}try{valid();showState();}catch(x){message(e.message);}return;}try{core.validate(j.token,config.public_key,device,Date.now()/1000,state.last_seen);state.token=j.token;state.last_seen=Math.floor(Date.now()/1000);save();showState();}catch(x){message(x.message);}});}
document.uzscribeLicense={allow:function(feature){try{valid(feature);state.last_seen=Math.max(state.last_seen||0,Math.floor(Date.now()/1000));if(config.mode==='subscription')save();return true;}catch(e){el('subscription').open=true;message(e.message);return false;}}};
el('licenseKey').value=state.key||'';el('activateLicense').onclick=function(){state.key=el('licenseKey').value.trim();state.token='';try{save();refresh();}catch(e){message(e.message);}};
el('refreshLicense').onclick=refresh;
var purchaseBusy=false;el('buyLicense').onclick=function(){if(purchaseBusy)return;if(!config.api_url){message('To‘lov serveri hali ulanmagan.');return;}purchaseBusy=true;el('buyLicense').disabled=true;var key=el('licenseKey').value.trim();state.key=key;request('/api/orders',{plan_id:el('licensePlan').value},function(e,j){purchaseBusy=false;el('buyLicense').disabled=false;if(e){message(e.message);return;}try{if(j.license_key){state.key=j.license_key;state.token='';el('licenseKey').value=state.key;save();}if(!/^https:\/\/checkout\.(test\.)?paycom\.uz\//.test(j.checkout_url))throw Error('To‘lov havolasi noto‘g‘ri.');__adobe_cep__.openURLInDefaultBrowser(j.checkout_url);message('Payme’da to‘lang, keyin “Holatni yangilash”ni bosing.'+(j.sandbox?' Sinov rejimi.':''));}catch(x){message(x.message);}});};
el('releaseLicense').onclick=function(){if(!state.key){message('Kalit kiriting.');return;}request('/api/devices/remove',{device_id:device},function(e){if(e){message(e.message);return;}state.token='';try{save();showState();}catch(x){message(x.message);}});};
if(config.api_url)request('/api/plans',null,function(e,j){if(e)return;el('licensePlan').textContent='';j.plans.forEach(function(p){var o=document.createElement('option');o.value=p.id;o.textContent=p.title+' · '+p.price_uzs.toLocaleString()+' so‘m';el('licensePlan').appendChild(o);});el('buyLicense').disabled=!j.payments_ready;});
refresh();setInterval(refresh,4*60*60*1000);
})();
